backend:
  name: git-gateway
  branch: master

media_folder: "public/uploads" # donde se guardarán las imágenes
public_folder: "/uploads"

collections:
  - name: "galeria"
    label: "Galería"
    folder: "src/content/galeria"
    create: true
    format: "json"
    fields:
      - { label: "Imagen", name: "src", widget: "image" }
      - { label: "Descripción", name: "alt", widget: "string" }
      - { label: "Categoría", name: "category", widget: "select", options: ["Cortes", "Local", "Producto"] }

