backend:
  name: git-gateway
  branch: master

media_folder: "public/uploads" # donde se guardarán las imágenes
public_folder: "/uploads"

collections:
  - name: "gallery"
    label: "Galería"
    folder: "content/gallery"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Imagen", name: "image", widget: "image" }
